# Fast compile times on macOS
[target.aarch64-apple-darwin]
rustflags = ["-C", "split-debuginfo=unpacked"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "split-debuginfo=unpacked"]

# Linux optimizations
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"